name: Deploy Nodejs Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug SSH Key (safe)
        run: |
          echo "SSH key line count:"
          echo "${{ secrets.SSH_KEY }}" | wc -l

      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          port: 22
          key: ${{ secrets.SSH_KEY }}
          debug: true
          script_stop: true
          script: |
            set -e
            echo "Connected to server: $(hostname)"
            whoami
            pwd

            cd /home/ubuntu/test-repo/test-ci-cd

            echo "Pulling latest code..."
            git pull origin main

            echo "Building & starting containers..."
            docker compose up -d --build

            echo "Deployment finished successfully"
